#application.yml
spring:
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
  profiles:
    active: db, jwt, payment, s3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      bucket: goalddae-bucket
      endpoint: https://kr.object.ncloudstorage.com
