#application.yml
spring:
  datasource:
    url: ENC(noYKCh1ox/mi553kaSZFeeiROmiceZQhomyeQaBycjM0X6XOfBUV3Qxx7Naadt9DJwr9D/vNwE5JtoO5XOOcsAg4WKWhbcmc2HAIncqYK4DigPyL8QLuQjg/PhYHCjQhUaaxcge//NLqWAcQ36amBG241vAXLuy+)
    username: ENC(LURQQHtySzlneKsw3Hn+PXpe1BgqUb5E)
    password: ENC(OxaxxXJaaTlZQjLGzdgupJ3d7gIdyl+SK2M1Atf6dwI=)
    driver-class-name: ENC(p2euEo/ESquHypoblIzaBc8Ehh/Sj3I/9oql4rv8/tctgPqc3/2GPQ==)
  #  profiles:
  #    active: db, jwt, payment, oauth2, s3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(P/7K09qzEucQLGwvt4We2WqBB6zlXKY8KHYh6fy67b8NmafBr9PifOX8WYBVY59Hzj5OrHAtssIPRM1jI5OsG9kjbiWyQljHlB7qsYbcCGTHyfEqq1z7QQ==)
            client-secret: ENC(Q5SAdZyMBaL67jPPq5W9OXYX3AHjvaw71eJKvtBUIN/9WQf/Dg0R0GMcjMEtuouI)
            scope: email, profile
          naver:
            client-id: ENC(zyxlVHUbmx++PuD6LW5lGSob2SjVfNWY0AJKYuHsWBc=)
            client-secret: ENC(Y03JpXjMKeIsha+jwn+YDq9nOk6v6cfA)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  issuer: ENC(E+N9b3EKadf9LRicOj5mrT9Obpgig7QO)
  secret_key: ENC(JwJtticd74aDGwDc9utYa93w+ZpRetRFoG2jTN8lhWQ=)

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(QPJrOWmGWeoQrISL3zfxBc/ef4kpTzSS1voSvNFrRJs=)
      secret-key: ENC(VUU4LjfVmLCe+rTCaXRYYR6nCX8GROfkMwN9ncE5xdzPd6Kz+n9tlDWru1vEdm1dxm0Z892fjb8=)
    s3:
      bucket: goalddae-bucket
      endpoint: https://kr.object.ncloudstorage.com

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
        prefix: ENC(
        suffix: )

mail:
  id: ENC(AJ6SjY3Nk9npJtus5XxU0Rw700FmNEDw4UncF9Vv+t8=)
  password: ENC(o6q11rKvtbcSeFldFrZQdIWbvETcc3UaddNFPoTcBZ8=)
  host: ENC(KES7aLN/AsXR+unJ+GrKQZbSefD0aXDg)
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

payment:
  franchise_key: ENC(08qjI2PFliLnN93vVrhw1o6V7oGBaAh+)
  rest_api_key: ENC(WOdM4O6pqiNA+Bo06rKaCwAzFfoobxiqTRsaZlmvnXc=)
  rest_api_secret: ENC(tFKIJVyCU9W8vrUCFcaFET3RccMdLfn4zbqroo1N3Y83+61iQ5ZWQsfGegxHPQYimC5czBb2GbiOGXYvqYkBawyfq53C4WxClV3n8OYgHVzz3T3W/81g6yqjbabFJf08)

kakaoDevelop:
    restApiKey: ENC(EGLsOFJn9JVTRoVWDXvWXcQAbzyHMLzDziJP27+/k5x1ChzSUOaVF43v38R1PQXr)

weather:
  secretKey: ENC(4o5Cn/aR8elZ6IxrSPoo1mnEaYQMXDKZReXIkOYXBx31y04c5fSEnpeJOr6EFUTjI50/Fr8JH2IebZSuHcHfyeKVHIBFS55GOCAuHNCkby676IrwP52p0j4X2vQsGrjgrKYtbLBueZSeen8NcLUNoQ==)