cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: jZwiWplbb1HL7esSY9cp
      secret-key: fHtGt60TEKfExXxQmWkHDxH8NvmpylId7U29HpJN
    s3:
      bucket: goalddae-bucket
      endpoint: https://kr.object.ncloudstorage.com
